version: "3.9"
services:
  aas-registry:
    image: eclipsebasyx/aas-registry:1.3.0
    ports:
      - "4000:4000"

  aas-repo:
    image: eclipsebasyx/aas-repository:1.3.0
    ports:
      - "4001:4001"

  submodel-repo:
    image: eclipsebasyx/submodel-repository:1.3.0
    ports:
      - "4002:4002"

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
